### ISSUE TITLE
End the execution after all buyers terminate

### ISSUE THREAD

**Issue by DharminB** [HBRS-MAAS/ws18-jade-tutorials-DharminB#4]
After all buyers terminate, the sellers and the container itself should terminate. The program itself runs perfectly in terminal, but travis will get stuck.

Cannot use `shutdown` behavious because that does not give time to buyers to buy 3 books.

For current progress please check [this](https://github.com/HBRS-MAAS/ws18-jade-tutorials-DharminB/tree/feature/added_complete_tutorial) branch.

For travis execution details, check [this](https://travis-ci.org/HBRS-MAAS/ws18-jade-tutorials-DharminB/builds/446930207)
@argenos please help !

**Comment by argenos** [comment]
You need a different termination conditions for each of the agents. 
As you said the buyers should terminate as soon as they buy their 3 books. 
For the sellers, you could use the yellow pages to find out how many buyers are there, and when that number is 0, they can shutdown.

**Comment by argenos** [comment]
As for the container, if I’m not mistaken you could kill it from the last seller agent before it shuts down itself.

**Comment by DharminB** [comment]
Alright, I will try that. Thanks.
